flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads/flysystem-test'
            public_url: '/uploads/flysystem-test'